route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'ses'
receivers:
  - name: 'ses'
    email_configs:
      - smarthost: email-smtp.us-east-1.amazonaws.com:587
        auth_username: AKIAXYKJVVFFMIYDKEZF
        auth_password: BK4rbc4Arw/N76+07D/KpUzPc1ajLYHozZZOGWZJy3Vo
        from: neelareddy.i0204@gmail.com
        to: neelareddy.i25@gmail.com
        headers:
          subject: Prometheus Mail Alert
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']